---
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtidy-dev
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.5
  - 2.5.3
  - 2.6
  - jruby-9.2.5.0
  - ree
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
